release:
  disable: false
builds:
    - env:
        - CGO_ENABLED=0
      goarch:
       - amd64
      goos:
       - windows
       - linux
       - darwin

nfpms:
    -
      # You can change the name of the package.
      # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
      name_template: "{{ .ProjectName }}"

      # Replacements for GOOS and GOARCH in the package name.
      # Keys should be valid GOOSs or GOARCHs.
      # Values are the respective replacements.
      # Default is empty.
      replacements:
        amd64: 64-bit
        386: 32-bit
        darwin: macOS

      license: Apache 2.0
      formats:
        - deb
        - rpm

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
